name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run cypress:run

      - name: Merge mochawesome JSONs
        run: npm run report:merge

      - name: Generate HTML report
        run: npm run report:generate

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports
