name: Cypress E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Ensure reports folder exists
      - name: Create reports folder
        run: mkdir -p cypress/reports

      # Step 5: Run Cypress tests headless (use config file for reporter)
      - name: Run Cypress tests
        run: npx cypress run --headless --browser chrome

      # Step 6: List JSON files (debug)
      - name: List JSON files
        run: ls -la cypress/reports/*.json || echo "No JSON files found"

      # Step 7: Generate HTML report from JSONs
      - name: Generate HTML report
        run: npx marge cypress/reports/*.json -f report -o cypress/reports --charts

      # Step 8: Upload Cypress report artifact
      - name: Upload Cypress report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports
