name: Cypress E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Create results folder
      - name: Create results folder
        run: mkdir -p cypress/results

      # Step 5: Run Cypress tests
      - name: Run Cypress tests
        run: npm run cypress:run

      # Step 6: Debug (optional) - list files to check JSONs
      - name: List results folder
        run: ls -la cypress/results

      # Step 7: Merge mochawesome JSONs
      - name: Merge mochawesome JSONs
        run: npm run report:merge

      # Step 8: Generate HTML report
      - name: Generate HTML report
        run: npm run report:generate

      # Step 9: Upload report as artifact
      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports
